components:
  headers:
    Date:
      description: Response date and time
      schema:
        format: date-time
        type: string
    Location:
      description: Location for the resource created/updated
      schema:
        type: string
  schemas:
    '400':
      properties:
        code:
          example: 400
          type: integer
        message:
          example: Enterprise Id is not found
          type: string
      type: object
    '401':
      properties:
        code:
          example: 401
          type: integer
        message:
          example: Authorization Header not found.
          type: string
        timestamp:
          example: trackingId_placeholder
          format: date-time
          type: string
        trackingId:
          example: trackingId_placeholder
          type: string
      type: object
    '403':
      properties:
        code:
          example: 403
          type: integer
        message:
          example: Forbidden
          type: string
        timestamp:
          example: trackingId_placeholder
          format: date-time
          type: string
        trackingId:
          example: trackingId_placeholder
          type: string
      type: object
    '500':
      properties:
        code:
          example: 500
          type: integer
        message:
          example: Something went wrong
          type: string
      type: object
    CreateTenantReq:
      properties:
        customer:
          example:
            customer_name: Foo Corporation
            initial_admin: kit@foo.com
          properties:
            customer_name:
              type: string
            initial_admin:
              type: string
          type: object
        enterprise_id:
          example: ab820f93-ba17-451d-8e4e-7da6ff8b8ff7
          type: string
        entitlements:
          items:
            example:
              enforce_quantity: true
              name: tier
              quantity:
                unit: users
                value: 32000
              value: advantage
            properties:
              enforce_quantity:
                type: boolean
              name:
                type: string
              quantity:
                properties:
                  unit:
                    type: string
                  value:
                    type: integer
                type: object
              value:
                type: string
            type: object
          type: array
        processing_meta:
          example:
            requestID: 3ee83993-448d-4a69-865e-ef93749dd19d
            send_welcome_email: false
          properties:
            requestID:
              type: string
            send_welcome_email:
              type: boolean
          type: object
        provisioning_metadata:
          example:
            - name: region
              value: APJC
          items:
            properties:
              name:
                type: string
              value:
                type: string
            type: object
          type: array
        schemas:
          items:
            example: urn:cisco:security:scim:tenant:core:1.0
          type: array
      type: object
    CreateTenantResp:
      properties:
        customer:
          example:
            customer_name: Foo Corporation
            initial_admin: kit@foo.com
          properties:
            customer_name:
              type: string
            initial_admin:
              type: string
          type: object
        enterprise_id:
          example: ab820f93-ba17-451d-8e4e-7da6ff8b8ff7
          type: string
        entitlements:
          items:
            example:
              enforce_quantity: true
              name: tier
              quantity:
                unit: users
                value: 32000
              value: advantage
            properties:
              enforce_quantity:
                type: boolean
              name:
                type: string
              quantity:
                properties:
                  unit:
                    type: string
                  value:
                    type: integer
                type: object
              value:
                type: string
            type: object
          type: array
        id:
          example: cff290b1-ed17-45a9-a47c-c6dce643715a
          type: string
        meta:
          example:
            created: '2023-11-20T10:24:58.516Z'
            lastModified: '2023-11-20T10:24:58.516Z'
            location: http://context-service-prod-svc.svc-commons:9090/context/provision/v1/Tenants/cff290b1-ed17-45a9-a47c-c6dce643715a
            resourceType: Tenant
          properties:
            created:
              format: date-time
              type: string
            lastModified:
              format: date-time
              type: string
            location:
              type: string
            resourceType:
              type: string
          type: object
        schemas:
          items:
            example: urn:cisco:security:scim:tenant:core:1.0
          type: array
      type: object
    UpdateTenantReq:
      properties:
        customer:
          example:
            customer_name: Foo Corporation
            initial_admin: kit@foo.com
          properties:
            customer_name:
              type: string
            initial_admin:
              type: string
          type: object
        enterprise_id:
          example: ab820f93-ba17-451d-8e4e-7da6ff8b8ff7
          type: string
        entitlements:
          items:
            example:
              enforce_quantity: true
              name: tier
              quantity:
                unit: users
                value: 32000
              value: advantage
            properties:
              enforce_quantity:
                type: boolean
              name:
                type: string
              quantity:
                properties:
                  unit:
                    type: string
                  value:
                    type: integer
                type: object
              value:
                type: string
            type: object
          type: array
        schemas:
          items:
            example: urn:cisco:security:scim:tenant:core:1.0
          type: array
      type: object
    UpdateTenantResp:
      properties:
        customer:
          example:
            customer_name: Foo Corporation
            initial_admin: kit@foo.com
          properties:
            customer_name:
              type: string
            initial_admin:
              type: string
          type: object
        enterprise_id:
          example: ab820f93-ba17-451d-8e4e-7da6ff8b8ff7
          type: string
        entitlements:
          items:
            example:
              enforce_quantity: true
              name: tier
              quantity:
                unit: users
                value: 32000
              value: advantage
            properties:
              enforce_quantity:
                type: boolean
              name:
                type: string
              quantity:
                properties:
                  unit:
                    type: string
                  value:
                    type: integer
                type: object
              value:
                type: string
            type: object
          type: array
        id:
          example: cff290b1-ed17-45a9-a47c-c6dce643715a
          type: string
        meta:
          example:
            lastModified: '2023-11-20T10:24:58.123Z'
            location: http://context-service-prod-svc.svc-commons:9090/context/provision/v1/Tenants/cff290b1-ed17-45a9-a47c-c6dce643715a
            resourceType: Tenant
          properties:
            lastModified:
              type: string
            location:
              type: string
            resourceType:
              type: string
          type: object
        schemas:
          items:
            example: urn:cisco:security:scim:tenant:core:1.0
          type: array
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      description: security scheme
      scheme: bearer
      type: http
info:
  description: '## Platform provisioning endpoint for Context Service'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Context Service Provisioning API
  version: 1.0.0
openapi: 3.0.3
paths:
  /Tenants:
    post:
      description: Create a tenant for provisioning
      operationId: createTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantReq'
        description: created
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTenantResp'
          description: Created
          headers:
            Date:
              $ref: '#/components/headers/Date'
            Location:
              $ref: '#/components/headers/Location'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
          description: Bad Request
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
          description: Unauthorized
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
          description: Forbidden
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
          description: Internal Server Error
          headers:
            Date:
              $ref: '#/components/headers/Date'
      security:
        - bearerAuth: []
      summary: Create Context Service Tenant
      tags:
        - Provision
  /Tenants/{id}:
    put:
      description: Update a tennat for provisining
      operationId: updateTenant
      parameters:
        - description: The ID of the tenant
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTenantReq'
        description: updated
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTenantResp'
          description: OK
          headers:
            Date:
              $ref: '#/components/headers/Date'
            Location:
              $ref: '#/components/headers/Location'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400'
          description: Bad Request
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/401'
          description: Unauthorized
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/403'
          description: Forbidden
          headers:
            Date:
              $ref: '#/components/headers/Date'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500'
          description: Internal Server Error
          headers:
            Date:
              $ref: '#/components/headers/Date'
      security:
        - bearerAuth: []
      summary: Update Context Service Tenant
      tags:
        - Provision
servers:
  - url: https://api.security.cisco.com/context/provision/v1
